### ISSUE TITLE
Changes to StationXML have created issues with strong motion responses

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/delta#134] opened 2017-09-03 22:24 UTC
I was just doing some work with FDSN and I can no longer remove the instrument response for strong motion data with obspy. 

If you look at these two FDSN queries the output is dramatically different. The original service from SC3 allows me to remove the response in obspy but the beta service does not. The beta service use to work. 

``http://service.geonet.org.nz/fdsnws/station/1/query?station=WTMC&location=20&channel=HNZ&level=response&starttime=2015-11-13T00:00:00.000``

``http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=WTMC&location=20&channel=HNZ&level=response&starttime=2015-11-13T00:00:00.000``

I have the same issue with other strong motion sites. 

@ozym I will email you with the jupyter notebook with my tests

**Comment by ozym** [comment] 2017-09-03 23:12
I've had a look and there appear to be differences between the stationxml file created from the repo and what it being provided by the service.

It appears that a response stage is missing, e.g.:

```
          </InstrumentSensitivity>                                        </InstrumentSensitivity>
                                                              >           <Stage number="1">
                                                              >             <PolesZeros resourceId="PolesZeros#CUSP SENSOR" n
                                                              >               <InputUnits>
                                                              >                 <Name>m/s**2</Name>
                                                              >               </InputUnits>
                                                              >               <OutputUnits>
                                                              >                 <Name>V</Name>
                                                              >               </OutputUnits>
                                                              >               <PzTransferFunctionType>LAPLACE (RADIANS/SECOND
                                                              >               <NormalizationFactor>1</NormalizationFactor>
                                                              >               <NormalizationFrequency>1</NormalizationFrequen
                                                              >             </PolesZeros>
                                                              >             <StageGain>
                                                              >               <Value>0.10197162129779283</Value>
                                                              >               <Frequency>1</Frequency>
                                                              >             </StageGain>
                                                              >           </Stage>
                                                              >           <Stage number="2">
                                                              >             <Coefficients resourceId="Coefficients#CUSP-200"
                                                              >               <InputUnits>
                                                              >                 <Name>V</Name>
                                                              >               </InputUnits>
                                                              >               <OutputUnits>
                                                              >                 <Name>count</Name>
                                                              >               </OutputUnits>
                                                              >               <CfTransferFunctionType>DIGITAL</CfTransferFunc
                                                              >             </Coefficients>
                                                              >             <Decimation>
                                                              >               <InputSampleRate>200</InputSampleRate>
                                                              >               <Factor>1</Factor>
                                                              >               <Offset>0</Offset>
                                                              >               <Delay>0</Delay>
                                                              >               <Correction>0</Correction>
                                                              >             </Decimation>
                                                              >             <StageGain>
                                                              >               <Value>1e+06</Value>
                                                              >               <Frequency>1</Frequency>
                                                              >             </StageGain>
                                                              >           </Stage>
        </Response>                                                     </Response>


```


There are also some non-standard (for now) dates, but these shouldn't be the problem, e.g.
```
<           <InstallationDate>2017-06-26T02:46:00Z</InstallationDate>
---
>           <InstallationDate>2017-06-26T02:46:00</InstallationDate>
```
Currently the `Z` shouldn't be there but this isn't the actual problem.

**Comment by ozym** [comment] 2017-09-03 23:25
@junghao it may be related to the Poles Zeros structure not having any Poles or Zeros defined.

**Comment by junghao** [comment] 2017-09-04 02:49
Tested the beta service:
http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=WTMC&location=20&channel=HNZ&level=response&starttime=2015-11-13T00:00:00.000
returns with 3 channels, but the 2nd channel (endDate="2017-06-26T02:45:00") has no stage under <response>.

Then I tried to reproduce the issue locally:
1. pull the delta repo
2. build and execute the binary tools/stationxml/stationxml, save the output as the data source for my local fdsn/station service.
3. query local service with parameter 
http://localhost:8080/fdsnws/station/1/query?station=WTMC&location=20&channel=HNZ&level=response&starttime=2015-11-13T00:00:00.000
4. The service returns 3 channels, each channel has <stage> under response. 

Any ideas? @nbalfour @ozym

**Comment by gclitheroe** [comment] 2017-09-04 11:22
I'm a bit confused by both @ozym and @junghao comments (sorry - staring at XML is confusing).  I can't see what is missing.

It's worth knowing that @nbalfour is having issues with using the response in obspy.  This is very exacting about parsing the XML so the non standard date times are highly likely to be the cause of the error even though they don't appear important to the data for the response.

What I am confused about is where the `Z` is coming from (`<InstallationDate>2010-03-26T02:30:00Z</InstallationDate>`) in the response from beta-service.  The `Z` is not in the input file (the result of running tools/stationxml/..) so is this getting added somehow in the fdsn-ws handling of the station.xml?

**Comment by junghao** [comment] 2017-09-04 20:48
@nbalfour @ozym @gclitheroe 
This morning I checked the request
http://beta-service.geonet.org.nz/fdsnws/station/1/query?station=WTMC&location=20&channel=HNZ&level=response&starttime=2015-11-13T00:00:00.000

Then I found that the missing `<stage>`  is back.
I guess it's the problem from source and has been updated automatically?

I'll fix the "Z" problem.

**Comment by nbalfour** [comment] 2017-09-05 00:02
Everything is working again now. Does anyone understand what the problem was?

**Comment by ozym** [comment] 2017-10-11 23:43
@gclitheroe if I recall correctly, this was related to reloading the stationxml file on the fly?

**Comment by gclitheroe** [comment] 2017-10-11 23:54
Yup this bug was recreated and fixed.  Closing.

**Closed by gclitheroe** 2017-10-11 23:54 UTC
Labels: bug
